"""empty message

Revision ID: 2f0b1450d9fb
Revises: 
Create Date: 2026-03-26 12:29:50.399841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0b1450d9fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartT',
    sa.Column('orderId', sa.String(length=10), nullable=False),
    sa.Column('lineNo', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('delFlg', sa.Boolean(), nullable=False),
    sa.Column('updDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('insDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('orderId', 'lineNo')
    )
    op.create_table('itemM',
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=30), nullable=True),
    sa.Column('itemName', sa.String(length=100), nullable=True),
    sa.Column('itemDetail', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('taxRate', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('recmdFlg', sa.Boolean(), nullable=True),
    sa.Column('imageName', sa.String(length=100), nullable=True),
    sa.Column('delFlg', sa.Boolean(), nullable=False),
    sa.Column('updDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('insDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_table('orderH',
    sa.Column('orderId', sa.String(length=10), nullable=False),
    sa.Column('orderDate', sa.String(length=10), nullable=True),
    sa.Column('userName', sa.String(length=50), nullable=True),
    sa.Column('orderAddress', sa.String(length=50), nullable=True),
    sa.Column('cardNum', sa.String(length=50), nullable=True),
    sa.Column('shipFlg', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('delFlg', sa.Boolean(), nullable=False),
    sa.Column('updDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('insDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.create_table('userM',
    sa.Column('userID', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('userName', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('delFlg', sa.Boolean(), nullable=False),
    sa.Column('updDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('insDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('orderD',
    sa.Column('orderId', sa.String(length=10), nullable=False),
    sa.Column('lineNo', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('delFlg', sa.Boolean(), nullable=False),
    sa.Column('updDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('insDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['orderH.orderId'], name='fk_orderD_orderH'),
    sa.PrimaryKeyConstraint('orderId', 'lineNo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderD')
    op.drop_table('userM')
    op.drop_table('orderH')
    op.drop_table('itemM')
    op.drop_table('cartT')
    # ### end Alembic commands ###
