"""empty message

Revision ID: 85b8db1c9cfb
Revises: 
Create Date: 2026-03-26 02:40:49.043459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b8db1c9cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderD', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orderD_orderH', 'orderH', ['orderId'], ['orderId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderD', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderD_orderH', type_='foreignkey')

    # ### end Alembic commands ###
